title: Joseph Cho
description: CS Senior @ Illinois
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github_url: https://github.com/mgjo5899
linkedin_url: https://www.linkedin.com/in/joseph-cho-b70465115/
